### ISSUE TITLE
希望在每个commit后自动生成一个apk

### ISSUE THREAD

**Issue by ghost** [ilufang/MMDump#3]
每次去编译一下实在太费劲了。。。
可不可以把编译的apk直接git上来或者搭个jenkins

**Comment by ilufang** [comment]
readme中有apk的百度盘链接。
[或者这里](pan.baidu.com/s/1bnxXUzX)
另此工程已不再更新,感谢你的建议.(我对GitHub也不是特别熟悉,以后我会放release里面)

**Comment by ilufang** [comment]
readme.md中有百度盘的apk下载链接
或者: [http://pan.baidu.com/s/1bnxXUzX](http://pan.baidu.com/s/1bnxXUzX)
此工程已不再更新.
感谢你的建议,我也正在探索GitHub的各种功能中,以后我会把对于的文件放在release中,谢谢.
